// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedIMClientSideTransport.proto
// Protobuf Java Version: 4.26.1

package com.xhs.redim.common.transport.protobuf.dto;

public final class RedIMClientSideTransportProto {
  private RedIMClientSideTransportProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RedIMClientSideTransportProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RedIMClientSideTransportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dto.RedIMClientSideTransport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
     * @return The type.
     */
    com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type getType();

    /**
     * <code>.dto.Ping ping = 2;</code>
     * @return Whether the ping field is set.
     */
    boolean hasPing();
    /**
     * <code>.dto.Ping ping = 2;</code>
     * @return The ping.
     */
    com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping getPing();
    /**
     * <code>.dto.Ping ping = 2;</code>
     */
    com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder getPingOrBuilder();

    com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.PayloadCase getPayloadCase();
  }
  /**
   * <pre>
   * 客户端发送
   * 服务端接收
   * </pre>
   *
   * Protobuf type {@code dto.RedIMClientSideTransport}
   */
  public static final class RedIMClientSideTransport extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dto.RedIMClientSideTransport)
      RedIMClientSideTransportOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        RedIMClientSideTransport.class.getName());
    }
    // Use RedIMClientSideTransport.newBuilder() to construct.
    private RedIMClientSideTransport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RedIMClientSideTransport() {
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_RedIMClientSideTransport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_RedIMClientSideTransport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.class, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Builder.class);
    }

    /**
     * Protobuf enum {@code dto.RedIMClientSideTransport.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          Type.class.getName());
      }
      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return PING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dto.RedIMClientSideTransport.Type)
    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PING(2),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 2: return PING;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type getType() {
      com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type result = com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type.forNumber(type_);
      return result == null ? com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type.UNRECOGNIZED : result;
    }

    public static final int PING_FIELD_NUMBER = 2;
    /**
     * <code>.dto.Ping ping = 2;</code>
     * @return Whether the ping field is set.
     */
    @java.lang.Override
    public boolean hasPing() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.dto.Ping ping = 2;</code>
     * @return The ping.
     */
    @java.lang.Override
    public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping getPing() {
      if (payloadCase_ == 2) {
         return (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_;
      }
      return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
    }
    /**
     * <code>.dto.Ping ping = 2;</code>
     */
    @java.lang.Override
    public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder getPingOrBuilder() {
      if (payloadCase_ == 2) {
         return (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_;
      }
      return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type.PING.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport)) {
        return super.equals(obj);
      }
      com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport other = (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport) obj;

      if (type_ != other.type_) return false;
      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 2:
          if (!getPing()
              .equals(other.getPing())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (payloadCase_) {
        case 2:
          hash = (37 * hash) + PING_FIELD_NUMBER;
          hash = (53 * hash) + getPing().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 客户端发送
     * 服务端接收
     * </pre>
     *
     * Protobuf type {@code dto.RedIMClientSideTransport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dto.RedIMClientSideTransport)
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_RedIMClientSideTransport_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_RedIMClientSideTransport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.class, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Builder.class);
      }

      // Construct using com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        if (pingBuilder_ != null) {
          pingBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_RedIMClientSideTransport_descriptor;
      }

      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport getDefaultInstanceForType() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.getDefaultInstance();
      }

      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport build() {
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport buildPartial() {
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport result = new com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
      }

      private void buildPartialOneofs(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 2 &&
            pingBuilder_ != null) {
          result.payload_ = pingBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport) {
          return mergeFrom((com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport other) {
        if (other == com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getPayloadCase()) {
          case PING: {
            mergePing(other.getPing());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getPingFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type getType() {
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type result = com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type.forNumber(type_);
        return result == null ? com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dto.RedIMClientSideTransport.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder> pingBuilder_;
      /**
       * <code>.dto.Ping ping = 2;</code>
       * @return Whether the ping field is set.
       */
      @java.lang.Override
      public boolean hasPing() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       * @return The ping.
       */
      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping getPing() {
        if (pingBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_;
          }
          return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return pingBuilder_.getMessage();
          }
          return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
        }
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      public Builder setPing(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      public Builder setPing(
          com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      public Builder mergePing(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping value) {
        if (pingBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance()) {
            payload_ = com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.newBuilder((com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            pingBuilder_.mergeFrom(value);
          } else {
            pingBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          pingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder getPingBuilder() {
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder getPingOrBuilder() {
        if ((payloadCase_ == 2) && (pingBuilder_ != null)) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_;
          }
          return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
        }
      }
      /**
       * <code>.dto.Ping ping = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
          }
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder>(
                  (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();
        return pingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:dto.RedIMClientSideTransport)
    }

    // @@protoc_insertion_point(class_scope:dto.RedIMClientSideTransport)
    private static final com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport();
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RedIMClientSideTransport>
        PARSER = new com.google.protobuf.AbstractParser<RedIMClientSideTransport>() {
      @java.lang.Override
      public RedIMClientSideTransport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RedIMClientSideTransport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RedIMClientSideTransport> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.RedIMClientSideTransport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dto.Ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string activeConvId = 1;</code>
     * @return A list containing the activeConvId.
     */
    java.util.List<java.lang.String>
        getActiveConvIdList();
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @return The count of activeConvId.
     */
    int getActiveConvIdCount();
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @param index The index of the element to return.
     * @return The activeConvId at the given index.
     */
    java.lang.String getActiveConvId(int index);
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the activeConvId at the given index.
     */
    com.google.protobuf.ByteString
        getActiveConvIdBytes(int index);
  }
  /**
   * Protobuf type {@code dto.Ping}
   */
  public static final class Ping extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dto.Ping)
      PingOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Ping.class.getName());
    }
    // Use Ping.newBuilder() to construct.
    private Ping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Ping() {
      activeConvId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_Ping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.class, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder.class);
    }

    public static final int ACTIVECONVID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList activeConvId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @return A list containing the activeConvId.
     */
    public com.google.protobuf.ProtocolStringList
        getActiveConvIdList() {
      return activeConvId_;
    }
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @return The count of activeConvId.
     */
    public int getActiveConvIdCount() {
      return activeConvId_.size();
    }
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @param index The index of the element to return.
     * @return The activeConvId at the given index.
     */
    public java.lang.String getActiveConvId(int index) {
      return activeConvId_.get(index);
    }
    /**
     * <code>repeated string activeConvId = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the activeConvId at the given index.
     */
    public com.google.protobuf.ByteString
        getActiveConvIdBytes(int index) {
      return activeConvId_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < activeConvId_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, activeConvId_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < activeConvId_.size(); i++) {
          dataSize += computeStringSizeNoTag(activeConvId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getActiveConvIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping)) {
        return super.equals(obj);
      }
      com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping other = (com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) obj;

      if (!getActiveConvIdList()
          .equals(other.getActiveConvIdList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActiveConvIdCount() > 0) {
        hash = (37 * hash) + ACTIVECONVID_FIELD_NUMBER;
        hash = (53 * hash) + getActiveConvIdList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dto.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dto.Ping)
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_Ping_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.class, com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.Builder.class);
      }

      // Construct using com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        activeConvId_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.internal_static_dto_Ping_descriptor;
      }

      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping getDefaultInstanceForType() {
        return com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance();
      }

      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping build() {
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping buildPartial() {
        com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping result = new com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          activeConvId_.makeImmutable();
          result.activeConvId_ = activeConvId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping) {
          return mergeFrom((com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping other) {
        if (other == com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping.getDefaultInstance()) return this;
        if (!other.activeConvId_.isEmpty()) {
          if (activeConvId_.isEmpty()) {
            activeConvId_ = other.activeConvId_;
            bitField0_ |= 0x00000001;
          } else {
            ensureActiveConvIdIsMutable();
            activeConvId_.addAll(other.activeConvId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureActiveConvIdIsMutable();
                activeConvId_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList activeConvId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureActiveConvIdIsMutable() {
        if (!activeConvId_.isModifiable()) {
          activeConvId_ = new com.google.protobuf.LazyStringArrayList(activeConvId_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @return A list containing the activeConvId.
       */
      public com.google.protobuf.ProtocolStringList
          getActiveConvIdList() {
        activeConvId_.makeImmutable();
        return activeConvId_;
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @return The count of activeConvId.
       */
      public int getActiveConvIdCount() {
        return activeConvId_.size();
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @param index The index of the element to return.
       * @return The activeConvId at the given index.
       */
      public java.lang.String getActiveConvId(int index) {
        return activeConvId_.get(index);
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the activeConvId at the given index.
       */
      public com.google.protobuf.ByteString
          getActiveConvIdBytes(int index) {
        return activeConvId_.getByteString(index);
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @param index The index to set the value at.
       * @param value The activeConvId to set.
       * @return This builder for chaining.
       */
      public Builder setActiveConvId(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureActiveConvIdIsMutable();
        activeConvId_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @param value The activeConvId to add.
       * @return This builder for chaining.
       */
      public Builder addActiveConvId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureActiveConvIdIsMutable();
        activeConvId_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @param values The activeConvId to add.
       * @return This builder for chaining.
       */
      public Builder addAllActiveConvId(
          java.lang.Iterable<java.lang.String> values) {
        ensureActiveConvIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activeConvId_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActiveConvId() {
        activeConvId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activeConvId = 1;</code>
       * @param value The bytes of the activeConvId to add.
       * @return This builder for chaining.
       */
      public Builder addActiveConvIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureActiveConvIdIsMutable();
        activeConvId_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dto.Ping)
    }

    // @@protoc_insertion_point(class_scope:dto.Ping)
    private static final com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping();
    }

    public static com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ping>
        PARSER = new com.google.protobuf.AbstractParser<Ping>() {
      @java.lang.Override
      public Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ping> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xhs.redim.common.transport.protobuf.dto.RedIMClientSideTransportProto.Ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dto_RedIMClientSideTransport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dto_RedIMClientSideTransport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dto_Ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dto_Ping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036RedIMClientSideTransport.proto\022\003dto\"\204\001" +
      "\n\030RedIMClientSideTransport\0220\n\004type\030\001 \001(\016" +
      "2\".dto.RedIMClientSideTransport.Type\022\031\n\004" +
      "ping\030\002 \001(\0132\t.dto.PingH\000\"\020\n\004Type\022\010\n\004PING\020" +
      "\000B\t\n\007Payload\"\034\n\004Ping\022\024\n\014activeConvId\030\001 \003" +
      "(\tBN\n+com.xhs.redim.common.transport.pro" +
      "tobuf.dtoB\035RedIMClientSideTransportProto" +
      "H\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dto_RedIMClientSideTransport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dto_RedIMClientSideTransport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dto_RedIMClientSideTransport_descriptor,
        new java.lang.String[] { "Type", "Ping", "Payload", });
    internal_static_dto_Ping_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dto_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dto_Ping_descriptor,
        new java.lang.String[] { "ActiveConvId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
